# Site Settings
title: Wai Phyo
logo: /docs/WaiPhyo.png # Path to the logo
description: My Portfolio in GitHub Page
show_downloads: false # Hide portfolio file download options

# Google Analytics (Replace with your actual Tracking ID)
google_analytics: UA-XXXXXXXXX-X

# Theme Settings
theme: minima # Switch to Minima Theme

# SASS Customization
sass:
  style: compressed # Compress CSS output

# Plugins
plugins:
  - jekyll-sass-converter # For processing SASS/SCSS files
  - jekyll-remote-theme # If needed for other themes

# Navigation Links (Menu bar links)
nav_links:
  - title: "About"
    url: "/about"
  - title: "Projects"
    url: "/projects"
  - title: "Skills"
    url: "/skills"
  - title: "Contact"
    url: "/contact"

# Defaults (Post Layout Defaults)
defaults:
  - scope:
      path: "" # Applies to all files
      type: "posts"
    values:
      layout: post
